export const BREAK_INCREMENT = 'BREAK_INCREMENT';
export const BREAK_DECREMENT = 'BREAK_DECREMENT';
export const SESSION_INCREMENT = 'SESSION_INCREMENT';
export const SESSION_DECREMENT = 'SESSION_DECREMENT';
export const RESET = 'RESET';
export const START_STOP = 'START_STOP';
export const COUNT_DOWN = 'COUNT_DOWN';
